allow-lan: false
bind-address: '*'
dns:
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  enable: true
  enhanced-mode: redir-host
  fallback:
  - https://208.67.222.222/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://101.6.6.6:8443/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
  listen: 0.0.0.0:53
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - 114.114.114.114
external-controller: 127.0.0.1:2671
secret: JCasbciSCBAISw
#ipv6: true
log-level: info
mixed-port: 2670
mode: rule
proxies: null
proxy-groups:
- name: connectivity
  type: select
  use:
  - TestConnectivity
- name: delay
  type: select
  use:
  - TestDelay
proxy-providers:
  TestConnectivity:
    path: ./test-connectivity.yaml
    type: file
  TestDelay:
    health-check:
      enable: true
      interval: 600000
      url: http://www.gstatic.com/generate_204
    path: ./test-delay.yaml
    type: file
rules:
- DOMAIN-SUFFIX,google.com,connectivity
- DOMAIN-KEYWORD,google,connectivity
- DOMAIN,google.com,connectivity
- DOMAIN-SUFFIX,bilibili.com,connectivity
- DOMAIN-KEYWORD,bilibili,connectivity
- DOMAIN,bilibili.com,connectivity
- DOMAIN-SUFFIX,microsoft.com,connectivity
- DOMAIN-SUFFIX,cachefly.net,connectivity
- DOMAIN-SUFFIX,apple.com,connectivity
- DOMAIN-SUFFIX,cdn-apple.com,connectivity
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- GEOIP,CN,DIRECT
- MATCH,connectivity
