allow-lan: false
bind-address: '*'
dns:
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  enable: true
  enhanced-mode: redir-host
  fallback:
  - https://208.67.222.222/dns-query
  - https://public.dns.iij.jp/dns-query
  - https://101.6.6.6:8443/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
  # listen: 0.0.0.0:53
  nameserver:
  - 119.29.29.29
  - 223.5.5.5
  - 114.114.114.114
external-controller: 127.0.0.1:2675
# secret: JCasbciSCBAISw
#ipv6: true
log-level: info
mixed-port: 2674
mode: rule
proxies: null
proxy-groups:
- name: default
  type: load-balance
  strategy: round-robin
  use:
  - Default
proxy-providers:
  Default:
    path: ../output/hk.yaml
    type: file
    interval: 600
rules:
- DOMAIN-SUFFIX,bilibili.com,default
- DOMAIN,bilibili.com,default
- SRC-IP-CIDR,192.168.1.201/32,DIRECT
- IP-CIDR,127.0.0.0/8,DIRECT
- MATCH,DIRECT
